#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nVous devez avoir les droits super-utilisateur pour executer $0"
	exit 1;
fi

echo "Installation des dépendances"
pip3 install paho-mqtt
pip3 install websocket-client
echo "Copie des fichiers necessaires"
if [ ! -d "/opt/maestro/" ];then
	mkdir /opt/maestro/
	chown -R $USER /opt/maestro/
	chmod -R 0755 /opt/maestro/
fi

cp _config_.py /opt/maestro
cp _data_.py /opt/maestro
cp maestro.py /opt/maestro

python3 /opt/maestro/maestro.py
