#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nVous devez avoir les droits super-utilisateur pour executer $0"
	exit 1;
fi

echo "Arret du service maestro"
systemctl stop maestro.service

echo "Copie des fichiers necessaires"
if [ ! -d "/opt/maestro/" ];then
	mkdir /opt/maestro/
	chown -R $USER /opt/maestro/
	chmod -R 0755 /opt/maestro/
fi

cp _data_.py /opt/maestro
cp maestro.py /opt/maestro
cp maestro.service /etc/systemd/system
chmod a+x /etc/systemd/system/maestro.service
echo "Redemarage du service, la fenetre pourra etre fermee."
systemctl --system daemon-reload
systemctl restart maestro.service
