#!/bin/sh

if [ $(whoami) != 'root' ]; then
	echo -e "\nInsuffiecent Rights. (Vous devez avoir les droits super-utilisateur pour executer $0)"
	exit 1;
fi

echo "Stopping service (Arret du service maestro)"
systemctl stop maestro.service

echo "Copy files. (Copie des fichiers necessaires)"
if [ ! -d "/opt/maestro/" ];then
	mkdir /opt/maestro/
	chown -R $USER /opt/maestro/
	chmod -R 0755 /opt/maestro/
fi

cp commands.py /opt/maestro
cp messages.py /opt/maestro
cp maestro.py /opt/maestro

cp maestro.service /etc/systemd/system
chmod a+x /etc/systemd/system/maestro.service
echo "Restarting service. (Redemarage du service, la fenetre pourra etre fermee.)"
systemctl --system daemon-reload
systemctl restart maestro.service
